/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blu;

import java.util.Date;

/**
 *
 * @author dell
 */
public class blu3 extends javax.swing.JFrame {

    /**
     * Creates new form blu3
     */
    public blu3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        gender1 = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        rday = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rtype = new javax.swing.JComboBox<>();
        rno = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        id = new javax.swing.JTextField();
        rtype1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\OneDrive\\Desktop\\java programs\\blu\\src\\blu\\2690553.jpg")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 500, 830));

        gender1.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        gender1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender1ActionPerformed(evt);
            }
        });
        jPanel1.add(gender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 200, 60));

        gender.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        gender.setForeground(new java.awt.Color(0, 0, 153));
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GENDER", "MALE", "FEMALE", "OTHER" }));
        gender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, 200, 60));

        rday.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        rday.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        jPanel1.add(rday, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 540, 150, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel4.setText(" OTHER FACILITIES");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 630, 230, 110));

        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 102));
        jButton2.setText("GENRATE RECIPT");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 780, 270, 50));

        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 102));
        jButton3.setText("CANCEL ");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 780, 150, 50));

        jButton5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 102));
        jButton5.setText("BACK");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 780, 150, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel5.setText("          CUSTOMER  NAME");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 360, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel6.setText("      CUSTOMER  MOBILE  NO.");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 360, 60));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel7.setText("      CUSTOMER  EMAIL  ADD.");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 360, 60));

        name.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, 390, 60));

        mobile.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        mobile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 140, 390, 60));

        email.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 240, 390, 60));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel8.setText("       CUSTOMER  ID  PROOF");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 360, 60));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel9.setText("      NO.  OF  DAYS");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 540, 250, 60));

        rtype.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        rtype.setForeground(new java.awt.Color(0, 0, 153));
        rtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ROOM TYPE", "SINGLE", "DOUBLE", "TRIPLE", "QUAD", "KING", "QUEEN", "APARTMENT" }));
        rtype.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        rtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtypeActionPerformed(evt);
            }
        });
        jPanel1.add(rtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 440, 220, 60));

        rno.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        rno.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        jPanel1.add(rno, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 540, 150, 60));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel12.setText("   NO. OF  ROOMS");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 540, 230, 60));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 153));
        jCheckBox1.setText("PARKING");
        jCheckBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 640, 140, 30));

        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(0, 0, 153));
        jCheckBox2.setText("Wi-Fi");
        jCheckBox2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 700, 120, 30));

        jCheckBox3.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(0, 0, 153));
        jCheckBox3.setText("LAUNDRY");
        jCheckBox3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 640, 130, 30));

        jCheckBox4.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(0, 0, 153));
        jCheckBox4.setText("BAR");
        jCheckBox4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 640, 110, 30));

        jCheckBox5.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(0, 0, 153));
        jCheckBox5.setText("FOOD");
        jCheckBox5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 640, 110, 30));

        jCheckBox6.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(0, 0, 153));
        jCheckBox6.setText("SWIMMING POOL");
        jCheckBox6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 700, 210, 30));

        jCheckBox7.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(0, 0, 153));
        jCheckBox7.setText("ROOM  SERVICE");
        jCheckBox7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 700, 210, 30));

        id.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 340, 390, 60));

        rtype1.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        rtype1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(rtype1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 440, 220, 60));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel2.setForeground(new java.awt.Color(51, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 0));
        jLabel2.setText("           WELCOME  TO  HOTEL  RADISSION  BLU,  INDORE");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 4));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 1100, 90));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel3.setForeground(new java.awt.Color(153, 255, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        area.setColumns(20);
        area.setFont(new java.awt.Font("NSimSun", 2, 18)); // NOI18N
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 390, 630));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("           CUSTOMER'S  BILL");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 390, 60));

        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("ADD");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 780, 150, 50));

        jButton4.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 102));
        jButton4.setText("PRINT");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 780, 150, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1484, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        blu2 ob=new blu2();
        ob.show();
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       area.setText("**************************************************************\n\n");
       area.setText(area.getText()+"                 HOTEL RADISSION BLU   \n");
       area.setText(area.getText()+"                     INDORE(MP)\n\n");
       Date ob=new Date();
       String date=ob.toString();
       area.setText(area.getText()+"   DATE: "+date+"\n");
       area.setText(area.getText()+"**************************************************************\n");
       area.setText(area.getText()+"CUSTOMER PERSONAL DETAILS:\n\n");
       area.setText(area.getText()+"CUSTOMER NAME         :  "+name.getText()+"\n");
       area.setText(area.getText()+"CUSTOMER MOBILE NO.   :  "+mobile.getText()+"\n");
       area.setText(area.getText()+"CUSTOMER EMAIL ADD.   :  "+email.getText()+"\n");
       area.setText(area.getText()+"CUSTOMER ID PROOF     :  "+id.getText()+"\n");
       area.setText(area.getText()+"GENDER                :  "+gender1.getText()+"\n");
       area.setText(area.getText()+"**************************************************************\n");
       area.setText(area.getText()+"ROOM DETAILS  :\n");
       area.setText(area.getText()+"ROOM TYPE             :  "+rtype.getSelectedItem().toString()+"\n");
       area.setText(area.getText()+"ROOM PRICE            :  "+rtype1.getText()+"\n");
       String s1=rno.getValue().toString();
       String s2=rday.getValue().toString();
       area.setText(area.getText()+"NO. OF ROOMS          :  "+s1+"\n");
       area.setText(area.getText()+"NO. OF DAYS TO STAY   :  "+s2+"\n");
       area.setText(area.getText()+"**************************************************************\n");
       area.setText(area.getText()+"YOUR BILL   :\n");
       double a1,a2,a3,a4,a5,b1,b2;
       a4=0;
       if(jCheckBox1.isSelected())
       {
           a4=a4+200;
       }
       if(jCheckBox2.isSelected())
       {
           a4=a4+200;
       }
       if(jCheckBox3.isSelected())
       {
           a4=a4+200;
       }
       if(jCheckBox4.isSelected())
       {
           a4=a4+200;
       }
       if(jCheckBox5.isSelected())
       {
           a4=a4+200;
       }
       if(jCheckBox6.isSelected())
       {
           a4=a4+200;
       }
       if(jCheckBox7.isSelected())
       {
           a4=a4+200;
       }
       a1=Double.parseDouble(rtype1.getText());
       b1=Double.parseDouble(s1);
       b2=Double.parseDouble(s2);
       a2=a1*b1*b2;
       a3=(a2*18)/100;
       a5=a2+a3+a4;
       area.setText(area.getText()+"AMOUNT WITHOUT TAX    :  "+a2+"\n");
       area.setText(area.getText()+"GST                   :  18%\n");
       area.setText(area.getText()+"TAX AMOUNT            :  "+a3+"\n");
       area.setText(area.getText()+"FACILITIES CHARGE     :  "+a4+"\n");
       area.setText(area.getText()+"TOTAL PAYABLE AMOUNT  :  "+a5+"\n");
       area.setText(area.getText()+"**************************************************************\n");
       area.setText(area.getText()+"                                 HAVE A NICE DAY\n");
       area.setText(area.getText()+"                                 PLEASE VISIT AGAIN\n");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        area.setText("");
        name.setText("");
        mobile.setText("");
        email.setText("");
        id.setText("");
        gender1.setText("");
        rtype1.setText("");
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(false);
        rno.setValue(0);
        rday.setValue(0);
        gender.setSelectedItem("GENDER");
        rtype.setSelectedItem("ROOM TYPE");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try
        {
            area.print();
        }
        catch(Exception e)
        {
            System.out.println("Exception handle");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        if(gender.getSelectedItem().equals("MALE"))
        {
            gender1.setText("MALE");
        }
        if(gender.getSelectedItem().equals("FEMALE"))
        {
            gender1.setText("FEMALE");
        }
        if(gender.getSelectedItem().equals("OTHER"))
        {
            gender1.setText("OTHER");
        }
    }//GEN-LAST:event_genderActionPerformed

    private void gender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gender1ActionPerformed

    private void rtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtypeActionPerformed
       if(rtype.getSelectedItem().equals("SINGLE"))
       {
           rtype1.setText("2500");
       }
       if(rtype.getSelectedItem().equals("DOUBLE"))
       {
           rtype1.setText("3000");
       }
       if(rtype.getSelectedItem().equals("TRIPLE"))
       {
           rtype1.setText("3500");
       }
       if(rtype.getSelectedItem().equals("QUAD"))
       {
           rtype1.setText("4000");
       }
       if(rtype.getSelectedItem().equals("KING"))
       {
           rtype1.setText("5000");
       }
       if(rtype.getSelectedItem().equals("QUEEN"))
       {
           rtype1.setText("4500");
       }
       if(rtype.getSelectedItem().equals("APARTMENT"))
       {
           rtype1.setText("8000");
       }
    }//GEN-LAST:event_rtypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(blu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(blu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(blu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(blu3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new blu3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField gender1;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField name;
    private javax.swing.JSpinner rday;
    private javax.swing.JSpinner rno;
    private javax.swing.JComboBox<String> rtype;
    private javax.swing.JTextField rtype1;
    // End of variables declaration//GEN-END:variables
}
